In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data

In [2]:
def init_weights(shape):
    return tf.Variable(tf.random_normal(shape, stddev=0.01))

In [3]:
def model(X, w_h, w_h2, w_o, p_keep_input, p_keep_hidden): # this network is the same as the previous one except with an extra hidden layer + dropout
    X = tf.nn.dropout(X, p_keep_input)
    h = tf.nn.relu(tf.matmul(X, w_h))

    h = tf.nn.dropout(h, p_keep_hidden)
    h2 = tf.nn.relu(tf.matmul(h, w_h2))

    h2 = tf.nn.dropout(h2, p_keep_hidden)

    return tf.matmul(h2, w_o)

In [4]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
trX, trY, teX, teY = mnist.train.images, mnist.train.labels, mnist.test.images, mnist.test.labels

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [5]:
X = tf.placeholder("float", [None, 784])
Y = tf.placeholder("float", [None, 10])

w_h = init_weights([784, 625])
w_h2 = init_weights([625, 625])
w_o = init_weights([625, 10])

p_keep_input = tf.placeholder("float")
p_keep_hidden = tf.placeholder("float")
py_x = model(X, w_h, w_h2, w_o, p_keep_input, p_keep_hidden)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=py_x, labels=Y))
train_op = tf.train.RMSPropOptimizer(0.001, 0.9).minimize(cost)
predict_op = tf.argmax(py_x, 1)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.



In [ ]:
# Launch the graph in a session
with tf.Session() as sess:
    # you need to initialize all variables
    tf.global_variables_initializer().run()

    for i in range(100):
        for start, end in zip(range(0, len(trX), 128), range(128, len(trX)+1, 128)):
            sess.run(train_op, feed_dict={X: trX[start:end], Y: trY[start:end],
                                          p_keep_input: 0.8, p_keep_hidden: 0.5})
        print(i, np.mean(np.argmax(teY, axis=1) ==
                         sess.run(predict_op, feed_dict={X: teX, Y: teY,
                                                         p_keep_input: 1.0,
                                                         p_keep_hidden: 1.0})))

# my original

In [6]:
def model(X, w_h, w_h2, w_o): # this network is the same as the previous one except with an extra hidden layer + dropout
    #X = tf.nn.dropout(X, p_keep_input)
    h = tf.nn.relu(tf.matmul(X, w_h))

    #h = tf.nn.dropout(h, p_keep_hidden)
    h2 = tf.nn.relu(tf.matmul(h, w_h2))

    #h2 = tf.nn.dropout(h2, p_keep_hidden)

    return tf.matmul(h2, w_o)

In [7]:
X = tf.placeholder("float", [None , 784])

In [8]:
Y = tf.placeholder("float" , [None , 10])

In [9]:
w_h = tf.Variable(tf.random_normal(shape=[784 , 100] , stddev=0.1))

In [10]:
w_h2 = tf.Variable(tf.random_normal(shape=[100,50] , stddev = 0.1))

In [11]:
w_o = tf.Variable(tf.random_normal(shape=[50,10] , stddev = 0.1))

In [12]:
py_x = model(X , w_h , w_h2, w_o)
type(py_x)

tensorflow.python.framework.ops.Tensor

In [13]:
cost_arg = tf.nn.softmax_cross_entropy_with_logits_v2(logits=py_x , labels=Y)
type(cost_arg)

tensorflow.python.framework.ops.Tensor

In [14]:
cost = tf.reduce_mean(cost_arg)
type(cost)

tensorflow.python.framework.ops.Tensor

reduce_meanはreduceするのではなくて単純にmeanを返す

In [22]:
?tf.reduce_mean


In [15]:
train_operation = tf.train.RMSPropOptimizer(0.001, 0.9).minimize(cost)

In [16]:
type(train_operation)

tensorflow.python.framework.ops.Operation

RMSProrは減速routineを組み込んだ勾配法（？）

In [17]:
?tf.train.RMSPropOptimizer

In [18]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

In [72]:
batch_size = 100
n_epoch = 50

In [99]:
for i in range(n_epoch):
    for z in zip(range(0 , len(trX) , batch_size) , range(batch_size , len(trX) + 1 , batch_size)):
        sess.run(train_operation , feed_dict={X:trX[z[0]:z[1]] , Y : trY[z[0]:z[1]]})
    predicted_decoded_teY = sess.run(tf.argmax(py_x, 1) , feed_dict = {X : teX})
    run_precision = np.mean(decoded_teY == predicted_decoded_teY)
    print(i , run_precision)

0 0.949
1 0.958
2 0.9624
3 0.9656
4 0.9675
5 0.9687
6 0.971
7 0.9706
8 0.9708
9 0.9682
10 0.9668
11 0.9644
12 0.9632
13 0.9643
14 0.9607
15 0.9594
16 0.9666
17 0.9659
18 0.9627
19 0.9671
20 0.9635
21 0.9696
22 0.968
23 0.9686
24 0.9692
25 0.9701
26 0.9671
27 0.9691
28 0.9734
29 0.9726
30 0.9731
31 0.9716
32 0.9709
33 0.9732
34 0.9723
35 0.9673
36 0.9727
37 0.9743
38 0.9729
39 0.9711
40 0.9718
41 0.9737
42 0.9728
43 0.9728
44 0.9728
45 0.9725
46 0.9734
47 0.9736
48 0.9717
49 0.9723


## sandbox

### tensorflow周り

In [67]:
sess.run(train_operation , feed_dict={X : trX[0:100] , Y : trY[0:100] })

In [20]:
sess.run(Y , feed_dict={X : trX[0:100] , Y : trY[0:100] }).shape

(100, 10)

In [68]:
decoded_teY = np.argmax(teY , axis=1)

In [95]:
for z in zip(range(0 , len(trX) , batch_size) , range(batch_size , len(trX) + 1 , batch_size)):
    sess.run(train_operation , feed_dict={X:trX[z[0]:z[1]] , Y : trY[z[0]:z[1]]})

In [96]:
predicted_decoded_teY = sess.run(tf.argmax(py_x, 1) , feed_dict = {X : teX})

In [97]:
run_precision = np.mean(decoded_teY == predicted_decoded_teY)

In [98]:
run_precision

0.9259

### range(start , end , by)

In [ ]:
range(0 , batch_size , )


In [89]:
[i for i in range(0 , 29 , 10)]

[0, 10, 20]

In [87]:
[i for i in range(10 , 30 , 10)]

[10, 20]

### zip は少ないほうに合わせる模様：

In [92]:
[z for z in zip(range(0,29,10),range(10,30,10))]

[(0, 10), (10, 20)]

In [83]:
len([i for i in range(batch_size, len(trX) + 1, batch_size)])

550

In [85]:
len([i for i in range(0, len(trX), batch_size)])

550

In [32]:
sess.run(tf.reduce_mean(tf.constant([[1,100],[1000,10000] ] , dtype = "float")))

2775.25

In [33]:
sess.run(tf.reduce_mean(tf.constant([[1,100],[1000,10000] ] , dtype = "float") ,axis=0))

array([ 500.5, 5050. ], dtype=float32)

In [35]:
sess.run(tf.reduce_mean(tf.constant([[1,100],[1000,10000] ] , dtype = "float") ,axis=0  , keep_dims=True))

array([[ 500.5, 5050. ]], dtype=float32)

In [36]:
sess.run(tf.reduce_mean(tf.constant([[1,100],[1000,10000] ] , dtype = "float") ,axis=1  , keep_dims=True))

array([[  50.5],
       [5500. ]], dtype=float32)